### ISSUE TITLE
error installing rosdep dependencies 

### ISSUE THREAD

**Issue by AyanHBK123** [frank26080115/HandHeld3DScanner#7]
I am trying to install rosdep dependencies on my pi buster but i kept getting this error. 
I am making Handheld 3D scanner and following your steps. 

**when i run this command** 
rosdep install -y --from-paths src --ignore-src --rosdistro kinetic -r --os=debian:buster

**I get this error**

Traceback (most recent call last):
  
File "/usr/bin/rosdep", line 6, in <module>
    from pkg_resources import load_entry_point
 
 File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
 
 File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
 
 File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
 
 File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
 
 File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
 
 File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)

pkg_resources.DistributionNotFound: The 'rosdistro>=0.7.5' distribution was not found and is required by rosdep

**Comment by AyanHBK123** [comment]
Initially I am getting this error:

python-rosdep-modules : 
Depends: python-catkin-pkg-modules (>= 0.4.0) but it is not going to be installed
Depends: python-rosdistro-modules (>= 0.7.5) but it is not going to be installed
 python-rospkg-modules : 
Depends: python-catkin-pkg-modules but it is not going to be installed

E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

and cannot find a solution to this
