### ISSUE TITLE
Getting Error while installing rtabmap_ros 

### ISSUE THREAD

**Issue by AyanHBK123** [frank26080115/HandHeld3DScanner#9]
I am following your guide from:
http://eleccelerator.com/wiki/index.php?title=Raspbian_Buster_ROS_RealSense 
and I am now installing rtabmap_ros but I am getting these error, 

when I run the command 
**catkin_make -j1 
I get this error** 

CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkin_workspace.cmake:100 (message):
  This workspace contains non-catkin packages in it, and catkin cannot build
  a non-homogeneous workspace without isolation.  Try the
  'catkin_make_isolated' command instead.
Call Stack (most recent call first):
  CMakeLists.txt:69 (catkin_workspace)

-- Configuring incomplete, errors occurred!
See also "/home/pi/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/catkin_ws/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:1526: cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

after getting this error I run the command 
**catkin_make_isolated
as mentioned in the error 
but this leads to this error** 

In file included from /home/pi/catkin_ws/src/tf_conversions/eigen_conversions/src/eigen_kdl.cpp:30:
/home/pi/catkin_ws/src/tf_conversions/eigen_conversions/include/eigen_conversions/eigen_kdl.h:40:10: fatal error: kdl/frames.hpp: No such file or directory
 #include <kdl/frames.hpp>
          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/eigen_conversions.dir/build.make:76: CMakeFiles/eigen_conversions.dir/src/eigen_kdl.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:402: CMakeFiles/eigen_conversions.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
<== Failed to process package 'eigen_conversions': 
  Command '['/home/pi/catkin_ws/devel_isolated/ddynamic_reconfigure/env.sh', 'make', '-j4', '-l4']' returned non-zero exit status 2

anyway to solve this problem ??

**Comment by frank26080115** [comment]
I can only guess, but maybe try running

    sudo apt-get install libeigen3-dev

If the eigen_conversions part is failing to build, maybe eigen3 or something eigen3 depends on isn't installed, so running apt-get on libeigen3-dev should install what is missing

Hope that works

**Comment by AyanHBK123** [comment]
Its latest version is already installed.

**Comment by frank26080115** [comment]
hmmm maybe figure out how to install the expected version of KDL?

https://orocos.org/wiki/Installation_Manual.html

**Comment by AyanHBK123** [comment]
well that worked for me using the link but I am getting this error: 

CMake Error at CMakeLists.txt:41 (add_subdirectory):
  The source directory

    /home/pi/catkin_ws/src/orocos_kinematics_dynamics/python_orocos_kdl/pybind11

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:42 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".


-- Configuring incomplete, errors occurred!
See also "/home/pi/catkin_ws/build_isolated/python_orocos_kdl/CMakeFiles/CMakeOutput.log".
See also "/home/pi/catkin_ws/build_isolated/python_orocos_kdl/CMakeFiles/CMakeError.log".
<== Failed to process package 'python_orocos_kdl': 
  Command '['/home/pi/catkin_ws/devel_isolated/orocos_kdl/env.sh', 'cmake', '/home/pi/catkin_ws/src/orocos_kinematics_dynamics/python_orocos_kdl', '-DCATKIN_DEVEL_PREFIX=/home/pi/catkin_ws/devel_isolated/python_orocos_kdl', '-DCMAKE_INSTALL_PREFIX=/home/pi/catkin_ws/install_isolated', '-G', 'Unix Makefiles']' returned non-zero exit status 1

**Comment by AyanHBK123** [comment]
> well that worked for me using the link but I am getting this error:
> 
> CMake Error at CMakeLists.txt:41 (add_subdirectory):
> The source directory
> 
> ```
> /home/pi/catkin_ws/src/orocos_kinematics_dynamics/python_orocos_kdl/pybind11
> ```
> 
> does not contain a CMakeLists.txt file.
> 
> CMake Error at CMakeLists.txt:42 (pybind11_add_module):
> Unknown CMake command "pybind11_add_module".
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/pi/catkin_ws/build_isolated/python_orocos_kdl/CMakeFiles/CMakeOutput.log".
> See also "/home/pi/catkin_ws/build_isolated/python_orocos_kdl/CMakeFiles/CMakeError.log".
> <== Failed to process package 'python_orocos_kdl':
> Command '['/home/pi/catkin_ws/devel_isolated/orocos_kdl/env.sh', 'cmake', '/home/pi/catkin_ws/src/orocos_kinematics_dynamics/python_orocos_kdl', '-DCATKIN_DEVEL_PREFIX=/home/pi/catkin_ws/devel_isolated/python_orocos_kdl', '-DCMAKE_INSTALL_PREFIX=/home/pi/catkin_ws/install_isolated', '-G', 'Unix Makefiles']' returned non-zero exit status 1

found this solution on this website, hope it help others :
https://www.intel.com/content/www/us/en/support/articles/000056851/software/development-software.html

**Comment by AyanHBK123** [comment]
so this is a new error I am getting now: 
CMake Warning:
  Manually-specified variables were not used by the project:

    CATKIN_DEVEL_PREFIX


-- Build files have been written to: /home/pi/catkin_ws/build_isolated/test_tf2
==> make -j4 -l4 in '/home/pi/catkin_ws/build_isolated/test_tf2'
Unhandled exception of type 'RuntimeError':
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/catkin/builder.py", line 1068, in build_workspace_isolated
    number=index + 1, of=len(ordered_packages)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/catkin/builder.py", line 760, in build_package
    "'\n  This sometimes occurs when a non-catkin package is "
RuntimeError: No env.sh file generated at: '/home/pi/catkin_ws/devel_isolated/test_tf2/env.sh'
  This sometimes occurs when a non-catkin package is interpreted as a catkin package.
  This can also occur when the cmake cache is stale, try --force-cmake.
<== Failed to process package 'test_tf2': 
  No env.sh file generated at: '/home/pi/catkin_ws/devel_isolated/test_tf2/env.sh'
  This sometimes occurs when a non-catkin package is interpreted as a catkin package.
  This can also occur when the cmake cache is stale, try --force-cmake.
Command failed, exiting.

**Comment by frank26080115** [comment]
I did some searching, maybe this will help

https://answers.ros.org/question/231666/catkin_make_isolated-does-not-create-envsh/

check if test_tf2 is indeed a catkin package, if it is not, apply the fix as suggested in the link I just posted

**Comment by AyanHBK123** [comment]
Thank you very much I have successfully installed rtabmap_ros, now I am on my last that is PCL 1.7. 
You have given how to solve the issue but an official guide install it is not given i have searched the web and now doing it from this link: 
https://answers.ros.org/question/229788/how-to-building-pcl-laser_scan_matcher-on-raspberry-pi-2/

but  this is for pi 2 , 
any suggestion regrading this ??

**Comment by frank26080115** [comment]
try https://pcl-tutorials.readthedocs.io/en/latest/compiling_pcl_posix.html

**Comment by AyanHBK123** [comment]
I following this guide but I keep getting this error:

i get this error when i do it with make command:
**cc1plus: out of memory allocating 1947960 bytes after a total of 139091968 bytes
make[2]: *** [sample_consensus/CMakeFiles/pcl_sample_consensus.dir/build.make:115: sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac_model_cone.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1143: sample_consensus/CMakeFiles/pcl_sample_consensus.dir/all] Error 2
make: *** [Makefile:152: all] Error 2**

and this error when do it with make -j2 
**c1plus: out of memory allocating 1947960 bytes after a total of 139014144 bytes
make[2]: *** [sample_consensus/CMakeFiles/pcl_sample_consensus.dir/build.make:115: sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac_model_cone.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Scanning dependencies of target pcl_hdl_grabber
[ 22%] Building CXX object io/tools/CMakeFiles/pcl_hdl_grabber.dir/hdl_grabber_example.cpp.o
make[1]: *** [CMakeFiles/Makefile2:1143: sample_consensus/CMakeFiles/pcl_sample_consensus.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 22%] Linking CXX executable ../../bin/pcl_hdl_grabber
[ 22%] Built target pcl_hdl_grabber
make: *** [Makefile:152: all] Error 2**

I am using Pi 4 8 GB ram but 32 GB SD card. 
I have already swap the ram to 2048 size and expanded file system .

**Comment by frank26080115** [comment]
Try -j1 for single threaded build, also maybe keep adding swap until you have enough

**Comment by AyanHBK123** [comment]
Thanks for all your help, 
We need a little help in the Case you made, 
What is the size of lid you made to fix the LCD screen for the pi. What is the size of LCD screen that will fit in the lid. 
To power the Pi did you use the C-type power or did you powered it using the pins ?

**Comment by AyanHBK123** [comment]
To power the Pi did you use the C-type power or did you powered it using the pins ?
